Time_zones/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.time_display.urls', namespace='time_display')),
    # url(r'^admin/', admin.site.urls),
]

apps/time_display/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^select_timezone/$', views.select_timezone, name="select_timezone"),

]

apps/time_display/models.py
from django.db import models

# Create your models here.

apps/time_display/views.py
from django.shortcuts import render, HttpResponse, redirect
# from datetime import datetime #this is needed for timenow
import datetime
from time import strftime

def index(request):
    print("This is index method in time_display views.py")
    time_zone = 0
    select = ["selected", "", "", "", "", "", ""]
    # timenow = datetime.now()

    central_time = datetime.datetime.now()
    central_time = central_time.strftime('%B %d, %Y %I:%M %p')
    this_time = central_time

    hawaii_time = datetime.datetime.now() - datetime.timedelta(hours=4)
    hawaii_time = hawaii_time.strftime('%B %d, %Y %I:%M %p')

    alaska_time = datetime.datetime.now() - datetime.timedelta(hours=3)
    alaska_time = alaska_time.strftime('%B %d, %Y %I:%M %p')

    pacific_time = datetime.datetime.now() - datetime.timedelta(hours=2)
    pacific_time = pacific_time.strftime('%B %d, %Y %I:%M %p')

    mountain_time = datetime.datetime.now() - datetime.timedelta(hours=1)
    mountain_time = mountain_time.strftime('%B %d, %Y %I:%M %p')

    eastern_time = datetime.datetime.now() + datetime.timedelta(hours=1)
    eastern_time = eastern_time.strftime('%B %d, %Y %I:%M %p')
    print("Hawaii time is:", hawaii_time)
    print("Alaska time is:", alaska_time)
    print("Pacific time is:", pacific_time)
    print("Mountain time is:", mountain_time)
    print("Central time is:", central_time)
    print("Eastern time is:", eastern_time)

    if 'time_zone' in request.session:
        print("Time zone is:", request.session['time_zone'])
        time_zone = request.session['time_zone']
        if int(time_zone) == 0:
            print("No zone was selected; default is Central time")
            this_time = central_time
            select = ["selected", "", "", "", "", "", ""]

        if int(time_zone) == 1:
            print("Zone is Hawaii time")
            this_time = hawaii_time
            select = ["", "selected", "", "", "", "", ""]

        if int(time_zone) == 2:
            print("Zone is Alaska time")
            this_time = alaska_time
            select = ["", "", "selected", "", "", "", ""]

        if int(time_zone) == 3:
            print("Zone is Pacific time")
            this_time = pacific_time
            select = ["", "", "", "selected", "", "", ""]

        if int(time_zone) == 4:
            print("Zone is Mountain time")
            this_time = mountain_time
            select = ["", "", "", "", "selected", "", ""]

        if int(time_zone) == 5:
            print("Zone is Central time")
            this_time = central_time
            select = ["", "", "", "", "", "selected", ""]

        if int(time_zone) == 6:
            print("Zone is Eastern time")
            this_time = eastern_time
            select = ["", "", "", "", "", "", "selected"]

    context = {
        # "time" : timenow,
        'time': this_time,
        'select': select,
    }
    # print("The time is", timenow)

    return render(request,'time_display/the_time.html', context)


def select_timezone(request):
    print("This is select_timezone method in time_display views.py")
    if request.method == 'POST':
        print("This is select_timezone POST method")
        request.session['time_zone'] = request.POST['time_zone']
        print("Time zone is:", request.session['time_zone'])

        return redirect('time_display:index')

    return redirect('time_display:index')

apps/time_display/templates/time_display/the_time.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'time_display/css/style.css' %}" media="screen">
    <title>Time Display</title>
  </head>

  <body>
    <fieldset>
      <legend>DATE AND TIME DISPLAY</legend>

      <div class="wrapper">

        <div class="column">
          <img src="{% static 'time_display/images/calendar_beige.jpg' %}" width="100%%" alt="image">
        </div>

        <div class="column2">

          <div class="time_display">
            <h4>The current date and time is:</h4>
            <h1>{{ time }}</h1>
          </div>

          <div class="time_select">
            <h4>Select your time zone:</h4>
            <form action = "{% url 'time_display:select_timezone' %}" method = "POST">
              {% csrf_token %}

              <input type="hidden" name="time" value="">
              <select name="time_zone">
                <option value="0" {{ select.0 }}>Choose one!</option>
                <option value="1" {{ select.1 }}>Hawaii time</option>
                <option value="2" {{ select.2 }}>Alaska time</option>
                <option value="3" {{ select.3 }}>Pacific time</option>
                <option value="4" {{ select.4 }}>Mountain time</option>
                <option value="5" {{ select.5 }}>Central time</option>
                <option value="6" {{ select.6 }}>Eastern time</option>
                <input type="submit" value="Submit">
              </select>
            </form>
          </div><!-- time_select end div -->

        </div><!-- column2 end div -->

        <div class="column">
          <img src="{% static 'time_display/images/clock3_beige.jpg' %}" width="100%%" alt="image">
        </div>

      </div><!-- wrapper end div -->

    </fieldset>

  </body>
</html>